### ISSUE TITLE
SUCCESS: Using CloudFlare DNS API

### ISSUE THREAD

**Issue by tackynugget** [alxwolf/ubios-cert#3]
I saw "Send a note if you succeeded with a different provider and I will list it here." on the [Readme](https://github.com/alxwolf/ubios-cert#currently-supported-dns-api-providers) file and thought I'd chime in with how I was able to get the CloudFlare API to work.

### Obtain your CloudFlare Token
1. Log into your CloudFlare account.
2. Click your avatar in the top right corner.
3. Click **My Profile** in the drop-down menu.
4. Click **API Tokens** in the left nav.
5. Click the **Create Token** button.
6. Navigate down to Create Custom Token and click the **Get Started** button.
7. Give your API token a descriptive name (it doesn't matter and you can change it later).
8. Under Permissions, set it to Zone - DNS - Edit
9. Under Zone Resources, set it to Include - Specific Zone - [the domain you want to use]
10. Configure TTL to your liking--can leave blank to make it indefinite.
11. Note the Token string. Guard it like a password.

### Obtain your CloudFlare Account ID
1. Exit **My Profile** and navigate to the domain you want to use.
2. Note your **Account ID** in the right nav.

### Edit your `/mnt/data/ubios-cert/ubios-cert.env` file
1. Duplicate this line (line 19 as of 2021-12-18) `DNS_API_PROVIDER="dns_kas"`
2. Comment out the original with an octothorp: `# DNS_API_PROVIDER="dns_kas"`
3. Replace `kas` with `cf` in the uncommented duplicate: `DNS_API_PROVIDER="dns_cf"`
4. Duplicate this line (line 33 as of 2021-12-18) `DNS_API_ENV="-e KAS_Login=w0xxxxx -e KAS_Authdata=abcd...efgh -e KAS_Authtype=sha1"`
5. Comment out the original with an octothorp
6. Populate the uncommented duplicate with your information: `DNS_API_ENV="-e CF_Token=TokenBlahBlah -e CF_Account_ID=AccountIDBlahBlah”`
7. Save and run (you might need to de-install and de-register and re-install for it to take effect--I've had some [trial and error](https://github.com/alxwolf/ubios-cert/issues/2) with this process)

I hope this helps!

**Comment by alxwolf** [comment]
THANK YOU @OverengineeredNetwork will add this to the README!

**Comment by alxwolf** [comment]
@OverengineeredNetwork PR done und merged, Wiki page created with your instructions. Thanks!

**Comment by tackynugget** [comment]
Thanks! Glad to help!
