### ISSUE TITLE
/mnt/data still hardcoded in ubios-cert.sh and 99-ubios-cert.sh

### ISSUE THREAD

**Issue by mojo333** [alxwolf/ubios-cert#31]
A good start but this should be re-opened as the scripts in `ubios-cert/ubios-cert.sh` and `ubios-cert/on_boot.d/99-ubios-cert.sh` also need to be updated to reflect the use of `/data` and not `/mnt/data` which is hardcoded in these scripts.

_Originally posted by @mojo333 in https://github.com/alxwolf/ubios-cert/issues/29#issuecomment-1354764763_

**Comment by alxwolf** [comment]
Isn't that covered in this command?

```
sed -i 's#/mnt/data#/data#g' "${SCRIPT_DIR}/ubios-cert/ubios-cert.env" "${SCRIPT_DIR}/ubios-cert/ubios-cert.sh" "${SCRIPT_DIR}/ubios-cert/on_boot.d/99-ubios-cert.sh"
```

**Comment by mojo333** [comment]
Missed that! Thanks - closing.
