### ISSUE TITLE
Add OVH as a DNS provider

### ISSUE THREAD

**Issue by Arnal95** [alxwolf/ubios-cert#42]
Hi, 
I succeeded to configure OVH as a DNS API Provider 

# OVH
export DNS_API_PROVIDER="dns_ovh"
export OVH_AK="ggdffettdgggdggd"
export OVH_AS="mlksdjfgmsjgkshgerhgz"
export OVH_CK="dlfkjhdmfgjozrhfgjozarhgoreaig"

**Comment by Arnal95** [comment]
https://github.com/acmesh-official/acme.sh/wiki/How-to-use-OVH-domain-api

**Comment by alxwolf** [comment]
Thank You @Arnal95, added a wiki page for it!
