### ISSUE TITLE
No such file or directory when running cd ${DATA_DIR}/ubios-cert

### ISSUE THREAD

**Issue by CaseyTal** [alxwolf/ubios-cert#44]
Hello, I'm trying to run the radius_cert_update branch but I'm getting stuck. 

I first attempted following the git command and just renaming that folder from ubios-cert-radius_cert_update to ubios-cert-main to just follow the guide line by line. However, when I got to the line: cd ${DATA_DIR}/ubios-cert , I got the warning: "-bash: cd: /ubios-cert: No such file or directory". Okay, no biggie. I typed cd /data and then cd ubios-cert. Then I tried running ./ubios-cert.sh initial and got the error: "./ubios-cert.sh: 42: /data/ubios-cert/ubios-cert.env: Syntax error: newline unexpected"

Not sure what I'm doing wrong here. I'm using Terminal on macOS to SSH in to a UDM Pro running v2.5.16. 

Thoughts? Also, not entirely sure what I need to change to update the radius certificate properly since the instructions mention to use the other branch, but no other details.

**Comment by alxwolf** [comment]
Oh let me have a look at that. This branch hasn't been touched since ages, will need to relearn that.

**Comment by CaseyTal** [comment]
Oh okay! I saw there were changes a couple of months ago, but I know 2.5 just came out a couple weeks ago.

Ultimately, I've got a site with multiple tenants connecting to the same WiFi network "The Golden" set up in WPA2-Enterprise signing in with their own usernames and passwords to get authenticated to their VLANs that are all isolated with each user only able to access their printers and devices.

The problem is that every time they connect, they get a warning that the certificate is untrusted and says "UbiOS". It would be nice to have a custom certificate with the name of the shared space so that people could know they could trust it.

So if I could install my own certificate, that would be ideal.

**Comment by CaseyTal** [comment]
My network version 7.3.83. Should I downgrade? Also using Terminal on Mac to SSH in. Should I be doing it another way?

**Comment by alxwolf** [comment]
Please don't change anything in your approach right now. I bet this is just broken for 2.x and needs to be fixed first. Will check that as soon as possible ...

**Comment by CaseyTal** [comment]
I appreciate it! Would be nice to stop getting bombarded with questions on why they're connecting to a "bad untrusted network". lol

**Comment by alxwolf** [comment]
Agree. "Usual" recommendation on reddit & co. is "just ignore it" or "type 'thisisnotsafe' in Chrome" etc.

Strongly dislike that as it educates the user to just ignore warnings when they should be respected...

**Comment by alxwolf** [comment]
continue in issue #14
