### ISSUE TITLE
ENABLE_RADIUS='yes' issue - cp: can't stat

### ISSUE THREAD

**Issue by tackynugget** [alxwolf/ubios-cert#5]
While troubleshooting #2 I noticed that when I set `ENABLE_RADIUS='yes'` in my `/mnt/data/ubios-cert/ubios-cert.env` file, I get a pair of `cp: can't stat` errors between the production of the certificate and the stopping of unifi-os (redacted my domain below) when I'm deploying a wildcard cert.
```
[Sun Dec 19 03:41:34 UTC 2021] And the full chain certs is there: /acme.sh/*.domain.tld/fullchain.cer
No new certificate was found, exiting without restart
**cp: can't stat '/mnt/data/ubios-cert/acme.sh/_.domain.tld/_.domain.tld.cer': No such file or directory
cp: can't stat '/mnt/data/ubios-cert/acme.sh/_.domain.tld/_.domain.tld.key': No such file or directory**
unifi-os: Stopping unifi-os
```

I haven't had time to figure out whether this poses an actual problem, but I assume it does. I'm not sure if something in how line 25 transforms the `CERT_NAME` variable: `ACME_CERT_NAME=${CERT_NAME/\*/_}`

This issue does not seem to occur when I specify subdomains.

My UDM-PRO is running 1.10.4; the Network is running 6.5.53

**Comment by alxwolf** [comment]
Thanks to the thorough documentation I've been able so fix this quickly by putting in right sequence.

**Comment by tackynugget** [comment]
Thank you for being so incredibly responsive @alxwolf!

I just uninstalled and reinstalled everything. 

I meant to test ENABLE_CAPTIVE #2 and ENABLE_RADIUS #5 separately, but accidentally tested them at the same time because of the cached version of my `ubios-cert.env` file. 

The ENABLE_RADIUS portion of the script appears to work. I named specific subdomains in this test.
