### ISSUE TITLE
Captive Portal

### ISSUE THREAD

**Issue by JayP1163** [alxwolf/ubios-cert#50]
Hello, I upgraded the firmware on my UDM-Pro OS Version 2.5.17 and Network 7.3.83 and updated the certificate with the newest version of this script. 

For some reason I’m getting the certificate error when accessing the captive portal. Not currently at the site to get the error but will be back on Saturday. But wanted to make sure if other users captive portal works? Making sure to see if I did something wrong. The older version of this script worked fine. I put ‘yes’ in the ENABLE_CAPTIVE and kept the ‘yes’ in the FULLCHAIN. I did not get an error when issuing the cert and it shows when checking the domain that the cert has been applied. 

Thank you

**Comment by JayP1163** [comment]
Sorry about that. The restart from the script did not deploy the certificate for the guest portal.  It was still using the unifi one. After a restart from the unifi portal of the UDM-Pro it fixed itself.

**Comment by paviln** [comment]
Hey. Same happend to me, thanks for the help ;)

**Comment by JayP1163** [comment]
> Hey. Same happend to me, thanks for the help ;)

Ahh good to hear, thanks for sharing
