### ISSUE TITLE
Can't open /data/unifi-core/config/unifi-core.crt for reading, No such file or directory

### ISSUE THREAD

**Issue by emilvissing** [alxwolf/ubios-cert#51]
Is this "+" symbol supposed to be there (at end of the line):
https://github.com/alxwolf/ubios-cert/blob/90732b4a81337d1114e98447c1f39f24a6eced43/ubios-cert/ubios-cert.sh#L61

**Comment by alxwolf** [comment]
Oh no, that was introduced by mistake. Will fix it, thanks for pointing it out.

**Comment by alxwolf** [comment]
@emilvissing should be ok now.
