### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by kb9gxk** [alxwolf/ubios-cert#52]
UniFi OS UDM SE 3.0.18
[Mon Mar 27 13:10:06 CDT 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Mon Mar 27 13:10:07 CDT 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Mon Mar 27 13:10:07 CDT 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Mon Mar 27 13:10:07 CDT 2023] No doh
[Mon Mar 27 13:10:07 CDT 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Mon Mar 27 13:10:07 CDT 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60

**Comment by alxwolf** [comment]
please provide more detail / output around when this happens.

My knee-jerk reaction on libcurl error 60 is pointing in [this direction](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) (expired Let's Encrypt Root CA). 

But that may be completely wrong, so please share what you are trying to do (initial, issue, renew?) with which certificate provider.

**Comment by kb9gxk** [comment]
I was trying to renew.  I believe that ended up being the issue.  I cleared the log files, grabbed the acme.sh from the source and it worked.

Using Cloudflare as my provider
