### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by unifinoob** [alxwolf/ubios-cert#54]
Hello, just installed this couple days ago and was wondering if there’s an option to add email notification when the certificate is renewed?

**Comment by alxwolf** [comment]
Yes, that is totally possibly by using whatever floats your boat from [´acme.sh´'s notify function](https://github.com/acmesh-official/acme.sh/wiki/notify).

you have a fully working `acme.sh` installation. To make it easily accessible, you could `ssh` into your UniFi console and issue:

```
ACMESH_ROOT="/data/ubios-cert/acme.sh"
ACME_HOME="--config-home ${ACMESH_ROOT} --cert-home ${ACMESH_ROOT} --home ${ACMESH_ROOT}"
alias acme.sh="${ACMESH_ROOT}/acme.sh ${ACMESH_CMD_PARAMS} ${ACME_HOME}"
```

With that, you can use something like `acme.sh --set-notify  --notify-hook <whatever hook you like>` from your command prompt. or start creating server certificates for other web servers you run...

I just put this in a [wiki entry](https://github.com/alxwolf/ubios-cert/wiki/Direct-access-to-´acme.sh´).

**Comment by unifinoob** [comment]
Thank you!
