### ISSUE TITLE
missing keytool?

### ISSUE THREAD

**Issue by rantanlan** [alxwolf/ubios-cert#59]
Issued the certificate perfectly fine, but installing doesn't work... it's missing the keytool binary? I wasn't able to find it anywhere on the machine?! did they remove java on it? I looked for openjk and apt is only showing release in an "oldstable" source... not sure if I'm supposed to install that!?

Dream Machine with
**UDM v3.1.16
Network 7.5.176**

`./ubios-cert.sh: line 69: keytool: command not found`
`./ubios-cert.sh: line 72: keytool: command not found`

**Comment by rantanlan** [comment]
I'm an idiot, had the captivate portal enabled in the env but don#t have any active on the udm. Working fine :)

**Comment by alxwolf** [comment]
@mason-xx glad to her it works!!
